#!/usr/bin/env bash
# Step 0a: UMLS MetamorphoSys 배치 모드로 서브셋 추출
#
# 전제조건:
#   - data/umls-2025AB-full.zip (NLM에서 다운로드)
#
# 사용법:
#   bash pipeline/step0a_setup_mmsys.sh
#
# 출력:
#   - data/umls_subset/2025AB/META/MRCONSO.RRF
#   - data/umls_subset/2025AB/META/MRREL.RRF
#   - data/umls_subset/2025AB/META/MRSTY.RRF
#   - ... (기타 RRF 파일)
#
# 소요시간: ~30-60분 (디스크 I/O 의존)
# 디스크: ~40GB 임시 공간 필요 (완료 후 정리 가능)

set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
UMLS_ZIP="${PROJECT_ROOT}/data/umls-2025AB-full.zip"
UMLS_DIR="${PROJECT_ROOT}/data/2025AB-full"
MMSYS_HOME="${UMLS_DIR}"
SUBSET_CONFIG="${UMLS_DIR}/subset.config.prop"
OUTPUT_DIR="${PROJECT_ROOT}/data/umls_subset"

echo "============================================================"
echo "Step 0a: UMLS MetamorphoSys 배치 서브셋 추출"
echo "============================================================"

# ──────────────────────────────────────────────────────────────
# 0. 출력 디렉토리 존재 확인 (이미 완료된 경우 skip)
# ──────────────────────────────────────────────────────────────
if [[ -f "${OUTPUT_DIR}/MRCONSO.RRF" ]]; then
    echo ""
    echo "[skip] ${OUTPUT_DIR}/MRCONSO.RRF 이미 존재합니다."
    echo "  다시 추출하려면: rm -rf ${OUTPUT_DIR}"
    echo ""
    wc -l "${OUTPUT_DIR}/MRCONSO.RRF" "${OUTPUT_DIR}/MRREL.RRF" "${OUTPUT_DIR}/MRSTY.RRF" 2>/dev/null || true
    exit 0
fi

# ──────────────────────────────────────────────────────────────
# 1. UMLS ZIP → .nlm 파일 추출
# ──────────────────────────────────────────────────────────────
if [[ ! -f "${UMLS_DIR}/2025ab-1-meta.nlm" ]]; then
    echo ""
    echo "[1/4] umls-2025AB-full.zip 압축 해제..."

    if [[ ! -f "${UMLS_ZIP}" ]]; then
        echo "ERROR: ${UMLS_ZIP} 파일이 없습니다."
        echo "NLM에서 다운로드: https://www.nlm.nih.gov/research/umls/licensedcontent/umlsknowledgesources.html"
        exit 1
    fi

    unzip -o "${UMLS_ZIP}" -d "${PROJECT_ROOT}/data/"
    echo "  완료: $(ls "${UMLS_DIR}"/*.nlm | wc -l) .nlm 파일"
else
    echo ""
    echo "[1/4] .nlm 파일 이미 존재 (skip)"
fi

# ──────────────────────────────────────────────────────────────
# 2. MetamorphoSys (mmsys.zip) 압축 해제
# ──────────────────────────────────────────────────────────────
if [[ ! -f "${MMSYS_HOME}/run_linux.sh" ]]; then
    echo ""
    echo "[2/4] mmsys.zip 압축 해제..."

    if [[ ! -f "${UMLS_DIR}/mmsys.zip" ]]; then
        echo "ERROR: ${UMLS_DIR}/mmsys.zip 파일이 없습니다."
        exit 1
    fi

    unzip -o "${UMLS_DIR}/mmsys.zip" -d "${MMSYS_HOME}/"
    chmod +x "${MMSYS_HOME}/run_linux.sh"
    chmod +x "${MMSYS_HOME}/jre/linux/bin/java"
    echo "  완료"
else
    echo ""
    echo "[2/4] MetamorphoSys 이미 설치됨 (skip)"
fi

# ──────────────────────────────────────────────────────────────
# 3. 서브셋 설정 파일 생성
# ──────────────────────────────────────────────────────────────
echo ""
echo "[3/4] 서브셋 설정 파일 생성..."

# user.a.prop을 기반으로 커스텀 설정 생성
# 원본에서 precedence, suppressible, unicode 설정을 가져옴
PRECEDENCE_LINE=$(grep "^gov.nih.nlm.umls.mmsys.filter.PrecedenceFilter.precedence=" \
    "${MMSYS_HOME}/config/2025AB/user.a.prop")
SUPPRESSIBLE_LINE=$(grep "^gov.nih.nlm.umls.mmsys.filter.SuppressibleFilter.suppressed_sabttys=" \
    "${MMSYS_HOME}/config/2025AB/user.a.prop")
UNICODE_LINE=$(grep "^gov.nih.nlm.umls.mmsys.filter.UnicodeFilter.char_map=" \
    "${MMSYS_HOME}/config/2025AB/user.a.prop")

mkdir -p "${OUTPUT_DIR}"

cat > "${SUBSET_CONFIG}" << 'PROP_HEADER'
# UMLS 2025AB Subset Configuration for Disease-Symptom KG
# Generated by step0a_setup_mmsys.sh
#
# 목적: 질환-증상 관계 KG 구축을 위한 최소 서브셋
# 포함 소스: SNOMEDCT_US, OMIM, MSH, HPO, NCI, MEDCIN, MTH,
#           ORPHANET, ICD10CM, ICD10, MEDLINEPLUS, MED-RT, CHV
# 언어: 영어만
PROP_HEADER

cat >> "${SUBSET_CONFIG}" << PROP_DIRS

meta_source_uri=${MMSYS_HOME}
umls_source_uri=${MMSYS_HOME}
meta_destination_uri=${OUTPUT_DIR}
umls_destination_uri=${OUTPUT_DIR}

release_version=2025AB

PROP_DIRS

cat >> "${SUBSET_CONFIG}" << 'PROP_SOURCES'
#
# Selected sources (KG 구축에 필요한 vocabulary만 선택)
#
# SNOMEDCT_US: 포괄적 임상 용어 (finding_site, has_associated_finding 등)
# OMIM: 유전 질환-증상 관계 (manifestation_of)
# MSH: MeSH (의학 주제 표제어)
# HPO: Human Phenotype Ontology (RareBench)
# NCI: NCI Thesaurus (disease_has_finding)
# MEDCIN: 임상 소견
# MTH: UMLS cross-reference
# ORPHANET: 희귀질환
# ICD10CM/ICD10: DDXPlus 매핑
# MEDLINEPLUS: 일반인용 의학 정보
# MED-RT: 약물-질환 관계
# CHV: Consumer Health Vocabulary
#
gov.nih.nlm.umls.mmsys.filter.SourceListFilter.selected_sources=SNOMEDCT_US|SNOMEDCT;MSH|MSH;OMIM|OMIM;HPO|HPO;NCI|NCI;MEDCIN|MEDCIN;MTH|MTH;ORPHANET|ORPHANET;ICD10CM|ICD10CM;ICD10|ICD10;MEDLINEPLUS|MEDLINEPLUS;MED-RT|MED-RT;CHV|CHV
PROP_SOURCES

# precedence, suppressible, unicode 설정 (원본 그대로)
echo "" >> "${SUBSET_CONFIG}"
echo "# Precedence (from user.a.prop)" >> "${SUBSET_CONFIG}"
echo "${PRECEDENCE_LINE}" >> "${SUBSET_CONFIG}"
echo "" >> "${SUBSET_CONFIG}"
echo "# Suppressible (from user.a.prop)" >> "${SUBSET_CONFIG}"
echo "${SUPPRESSIBLE_LINE}" >> "${SUBSET_CONFIG}"

cat >> "${SUBSET_CONFIG}" << 'PROP_LANG'

#
# Language: English only
#
gov.nih.nlm.umls.mmsys.filter.LanguagesFilter.selected_languages=ENG

#
# Semantic Types: 모든 시맨틱 타입 포함 (비우면 전체 포함)
#
gov.nih.nlm.umls.mmsys.filter.SemanticTypesFilter.selected_semantic_types=

#
# Relations: 모든 관계 유형 포함
#
gov.nih.nlm.umls.mmsys.filter.RelationsFilter.selected_relation_types=
gov.nih.nlm.umls.mmsys.filter.RelationsFilter.remove_selected_rels=true

#
# Attributes: 모든 속성 포함
#
gov.nih.nlm.umls.mmsys.filter.AttributesFilter.selected_attribute_types=
gov.nih.nlm.umls.mmsys.filter.AttributesFilter.remove_selected_attributes=true

#
# Content Views
#
gov.nih.nlm.umls.mmsys.filter.ContentViewFilter.selected_views=

#
# Unicode Filter
#
gov.nih.nlm.umls.mmsys.filter.UnicodeFilter.convert_unicode_char=true
PROP_LANG

echo "${UNICODE_LINE}" >> "${SUBSET_CONFIG}"

cat >> "${SUBSET_CONFIG}" << 'PROP_OUTPUT'

#
# Subset metadata
#
name=Disease-Symptom KG Subset
description=Medical vocabularies for disease-symptom KG (ENG only)

#
# Input Stream: NLM file format (.nlm archives)
#
mmsys_input_stream=gov.nih.nlm.umls.mmsys.io.NLMFileMetamorphoSysInputStream
gov.nih.nlm.umls.mmsys.io.RRFMetamorphoSysInputStream.enable_efficient=true
gov.nih.nlm.umls.mmsys.io.NLMFileMetamorphoSysInputStream.enable_efficient=true

#
# Output Stream: RRF format
#
mmsys_output_stream=gov.nih.nlm.umls.mmsys.io.RRFMetamorphoSysOutputStream

gov.nih.nlm.umls.mmsys.io.RRFMetamorphoSysOutputStream.database=
gov.nih.nlm.umls.mmsys.io.RRFMetamorphoSysOutputStream.versioned_output=false
gov.nih.nlm.umls.mmsys.io.RRFMetamorphoSysOutputStream.max_field_length=4000
gov.nih.nlm.umls.mmsys.io.RRFMetamorphoSysOutputStream.truncate=false
gov.nih.nlm.umls.mmsys.io.RRFMetamorphoSysOutputStream.remove_utf8=false
gov.nih.nlm.umls.mmsys.io.RRFMetamorphoSysOutputStream.remove_mth_only=false
gov.nih.nlm.umls.mmsys.io.RRFMetamorphoSysOutputStream.calculate_md5s=false
gov.nih.nlm.umls.mmsys.io.RRFMetamorphoSysOutputStream.add_unicode_bom=false
gov.nih.nlm.umls.mmsys.io.RRFMetamorphoSysOutputStream.character_encoding=UTF-8
gov.nih.nlm.umls.mmsys.io.RRFMetamorphoSysOutputStream.build_indexes=true

gov.nih.nlm.umls.mmsys.io.ORFMetamorphoSysOutputStream.database=
gov.nih.nlm.umls.mmsys.io.ORFMetamorphoSysOutputStream.versioned_output=false
gov.nih.nlm.umls.mmsys.io.ORFMetamorphoSysOutputStream.max_field_length=4000
gov.nih.nlm.umls.mmsys.io.ORFMetamorphoSysOutputStream.truncate=false
gov.nih.nlm.umls.mmsys.io.ORFMetamorphoSysOutputStream.remove_utf8=false
gov.nih.nlm.umls.mmsys.io.ORFMetamorphoSysOutputStream.remove_mth_only=false
gov.nih.nlm.umls.mmsys.io.ORFMetamorphoSysOutputStream.calculate_md5s=false
gov.nih.nlm.umls.mmsys.io.ORFMetamorphoSysOutputStream.add_unicode_bom=false
gov.nih.nlm.umls.mmsys.io.ORFMetamorphoSysOutputStream.character_encoding=UTF-8
gov.nih.nlm.umls.mmsys.io.ORFMetamorphoSysOutputStream.build_indexes=true

#
# Advanced Options
#
gov.nih.nlm.umls.mmsys.filter.SourceListFilter.enforce_family_selection=true
gov.nih.nlm.umls.mmsys.filter.SourceListFilter.enforce_dep_source_selection=true
gov.nih.nlm.umls.mmsys.filter.SourceListFilter.remove_selected_sources=false
gov.nih.nlm.umls.mmsys.filter.SourceListFilter.base_url=http://www.nlm.nih.gov/research/umls/sourcereleasedocs/
gov.nih.nlm.umls.mmsys.filter.SourceListFilter.ip_associations=
automatic_selection=false
gov.nih.nlm.umls.mmsys.filter.SuppressibleFilter.remove_source_tty_suppressible_data=false
gov.nih.nlm.umls.mmsys.filter.SuppressibleFilter.remove_editor_suppressible_data=false
gov.nih.nlm.umls.mmsys.filter.SuppressibleFilter.remove_obsolete_data=false

gov.nih.nlm.umls.mmsys.filter.PrecedenceFilter.cut_mode=false
gov.nih.nlm.umls.mmsys.filter.SemanticTypesFilter.any_sty=true
gov.nih.nlm.umls.mmsys.filter.SemanticTypesFilter.remove_selected_stys=true
gov.nih.nlm.umls.mmsys.filter.SourceTermTypesFilter.remove_selected_sabtty=true
gov.nih.nlm.umls.mmsys.filter.SourceTermTypesFilter.selected_sabttys=

active_filters=gov.nih.nlm.umls.mmsys.filter.SourceListFilter;gov.nih.nlm.umls.mmsys.filter.PrecedenceFilter;gov.nih.nlm.umls.mmsys.filter.SuppressibleFilter
PROP_OUTPUT

echo "  설정 파일: ${SUBSET_CONFIG}"
echo "  입력: ${MMSYS_HOME}"
echo "  출력: ${OUTPUT_DIR}"

# ──────────────────────────────────────────────────────────────
# 4. MetamorphoSys 배치 모드 실행
# ──────────────────────────────────────────────────────────────
echo ""
echo "[4/4] MetamorphoSys 배치 서브셋 실행..."
echo "  (30-60분 소요, 로그: ${UMLS_DIR}/mmsys.log)"
echo ""

cd "${MMSYS_HOME}"

CLASSPATH=".:lib/jpf-boot.jar"
export CLASSPATH

# boot.properties를 subset 모드로 교체 (JPF는 classpath root의 boot.properties를 사용)
if [[ ! -f boot.properties.gui.bak ]]; then
    cp boot.properties boot.properties.gui.bak
fi
cp etc/subset.boot.properties boot.properties

# 번들 JRE 사용 (Java 8, MetamorphoSys 공식 지원)
# 시스템 Java 17은 호환성 문제 가능
if [[ -x "${MMSYS_HOME}/jre/linux/bin/java" ]]; then
    JAVA_CMD="${MMSYS_HOME}/jre/linux/bin/java"
    echo "  Java: 번들 JRE (${JAVA_CMD})"
else
    JAVA_CMD="java"
    echo "  Java: 시스템 Java ($(java -version 2>&1 | head -1))"
fi

"${JAVA_CMD}" \
    -Dfile.encoding=UTF-8 \
    -Xms1000M -Xmx4000M \
    -Djava.awt.headless=true \
    -Dscript_type=.sh \
    -Dunzip.native=true \
    -Dunzip.path=/usr/bin/unzip \
    -Dinput.uri="${MMSYS_HOME}" \
    -Doutput.uri="${OUTPUT_DIR}" \
    -Dmmsys.config.uri="${SUBSET_CONFIG}" \
    org.java.plugin.boot.Boot \
    2>&1 | tee "${UMLS_DIR}/mmsys.log"

# boot.properties 원복
cp boot.properties.gui.bak boot.properties

cd "${PROJECT_ROOT}"

# ──────────────────────────────────────────────────────────────
# 5. 결과 검증
# ──────────────────────────────────────────────────────────────
echo ""
echo "============================================================"
echo "추출 결과 검증"
echo "============================================================"

for RRF in MRCONSO.RRF MRREL.RRF MRSTY.RRF MRDEF.RRF; do
    FILE="${OUTPUT_DIR}/${RRF}"
    if [[ -f "${FILE}" ]]; then
        LINES=$(wc -l < "${FILE}")
        SIZE=$(du -h "${FILE}" | cut -f1)
        echo "  ✓ ${RRF}: ${LINES} lines, ${SIZE}"
    else
        echo "  ✗ ${RRF}: 없음"
    fi
done

# ──────────────────────────────────────────────────────────────
# 6. 기존 파이프라인 호환 심볼릭 링크
# ──────────────────────────────────────────────────────────────
COMPAT_DIR="${PROJECT_ROOT}/data/umls_extracted"
if [[ -d "${OUTPUT_DIR}" ]] && [[ ! -e "${COMPAT_DIR}" ]]; then
    echo ""
    echo "기존 파이프라인 호환 심볼릭 링크 생성..."
    ln -s "${OUTPUT_DIR}" "${COMPAT_DIR}"
    echo "  ${COMPAT_DIR} → ${OUTPUT_DIR}"
elif [[ -L "${COMPAT_DIR}" ]]; then
    echo ""
    echo "심볼릭 링크 이미 존재: ${COMPAT_DIR}"
fi

echo ""
echo "완료!"
echo ""
echo "다음 단계:"
echo "  uv run python pipeline/step1b_build_umls_full_kg.py"
echo ""
echo "참고: 디스크 절약을 위해 .nlm 원본 삭제 가능:"
echo "  rm -f ${UMLS_DIR}/2025ab-*.nlm"
